var failures=new List<string>();

void Check(bool condition,string message)
{
    if(!condition)
        failures.Add(message);
}

await ClientProductionWorkspace1HundredStageSmoke.RunAsync(Check);
await ClientProductionWorkspace2HundredStageSmoke.RunAsync(Check);
await ClientProductionWorkspace3HundredStageSmoke.RunAsync(Check);
await ClientProductionWorkspace4HundredStageSmoke.RunAsync(Check);
await ClientProductionWorkspace5HundredStageSmoke.RunAsync(Check);

await ClientProductionReplaySnapshot1HundredStageSmoke.RunAsync(Check);
await ClientProductionReplaySnapshot2HundredStageSmoke.RunAsync(Check);
await ClientProductionReplaySnapshot3HundredStageSmoke.RunAsync(Check);
await ClientProductionReplaySnapshot4HundredStageSmoke.RunAsync(Check);
await ClientProductionReplaySnapshot5HundredStageSmoke.RunAsync(Check);

await ClientReleaseProjection1HundredStageSmoke.RunAsync(Check);
await ClientReleaseProjection2HundredStageSmoke.RunAsync(Check);
await ClientReleaseProjection3HundredStageSmoke.RunAsync(Check);
await ClientReleaseProjection4HundredStageSmoke.RunAsync(Check);
await ClientReleaseProjection5HundredStageSmoke.RunAsync(Check);

await ClientProductionRunHistory1HundredStageSmoke.RunAsync(Check);
await ClientProductionRunHistory2HundredStageSmoke.RunAsync(Check);
await ClientProductionRunHistory3HundredStageSmoke.RunAsync(Check);
await ClientProductionRunHistory4HundredStageSmoke.RunAsync(Check);
await ClientProductionRunHistory5HundredStageSmoke.RunAsync(Check);

await ClientRoiInteractionWorkspace1HundredStageSmoke.RunAsync(Check);
await ClientRoiInteractionWorkspace2HundredStageSmoke.RunAsync(Check);
await ClientRoiInteractionWorkspace3HundredStageSmoke.RunAsync(Check);
await ClientRoiInteractionWorkspace4HundredStageSmoke.RunAsync(Check);
await ClientRoiInteractionWorkspace5HundredStageSmoke.RunAsync(Check);

await ClientInspectionWorkspace1HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspace2HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspace3HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspace4HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspace5HundredStageSmoke.RunAsync(Check);

await ClientInspectionWorkspaceControl1HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspaceControl2HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspaceControl3HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspaceControl4HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkspaceControl5HundredStageSmoke.RunAsync(Check);

await ClientInspectionDiagnostics1HundredStageSmoke.RunAsync(Check);
await ClientInspectionDiagnostics2HundredStageSmoke.RunAsync(Check);
await ClientInspectionDiagnostics3HundredStageSmoke.RunAsync(Check);
await ClientInspectionDiagnostics4HundredStageSmoke.RunAsync(Check);
await ClientInspectionDiagnostics5HundredStageSmoke.RunAsync(Check);

await ClientRunHistoryPresentation1HundredStageSmoke.RunAsync(Check);
await ClientRunHistoryPresentation2HundredStageSmoke.RunAsync(Check);
await ClientRunHistoryPresentation3HundredStageSmoke.RunAsync(Check);
await ClientRunHistoryPresentation4HundredStageSmoke.RunAsync(Check);
await ClientRunHistoryPresentation5HundredStageSmoke.RunAsync(Check);

await ClientCommandAvailability1HundredStageSmoke.RunAsync(Check);
await ClientCommandAvailability2HundredStageSmoke.RunAsync(Check);
await ClientCommandAvailability3HundredStageSmoke.RunAsync(Check);
await ClientCommandAvailability4HundredStageSmoke.RunAsync(Check);
await ClientCommandAvailability5HundredStageSmoke.RunAsync(Check);

await ClientRoiHistoryControl1HundredStageSmoke.RunAsync(Check);
await ClientRoiHistoryControl2HundredStageSmoke.RunAsync(Check);
await ClientRoiHistoryControl3HundredStageSmoke.RunAsync(Check);
await ClientRoiHistoryControl4HundredStageSmoke.RunAsync(Check);
await ClientRoiHistoryControl5HundredStageSmoke.RunAsync(Check);

await ClientProgramWorkspace1HundredStageSmoke.RunAsync(Check);
await ClientProgramWorkspace2HundredStageSmoke.RunAsync(Check);
await ClientProgramWorkspace3HundredStageSmoke.RunAsync(Check);
await ClientProgramWorkspace4HundredStageSmoke.RunAsync(Check);
await ClientProgramWorkspace5HundredStageSmoke.RunAsync(Check);

await ClientWorkspaceRuntime1HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceRuntime2HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceRuntime3HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceRuntime4HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceRuntime5HundredStageSmoke.RunAsync(Check);

await ClientWorkspaceCommandRouting1HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceCommandRouting2HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceCommandRouting3HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceCommandRouting4HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceCommandRouting5HundredStageSmoke.RunAsync(Check);

await ClientProgramPresentation1HundredStageSmoke.RunAsync(Check);
await ClientProgramPresentation2HundredStageSmoke.RunAsync(Check);
await ClientProgramPresentation3HundredStageSmoke.RunAsync(Check);
await ClientProgramPresentation4HundredStageSmoke.RunAsync(Check);
await ClientProgramPresentation5HundredStageSmoke.RunAsync(Check);

await ClientWorkspaceLifecycle1HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceLifecycle2HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceLifecycle3HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceLifecycle4HundredStageSmoke.RunAsync(Check);
await ClientWorkspaceLifecycle5HundredStageSmoke.RunAsync(Check);

await ClientResultsPresentation1HundredStageSmoke.RunAsync(Check);
await ClientResultsPresentation2HundredStageSmoke.RunAsync(Check);
await ClientResultsPresentation3HundredStageSmoke.RunAsync(Check);
await ClientResultsPresentation4HundredStageSmoke.RunAsync(Check);
await ClientResultsPresentation5HundredStageSmoke.RunAsync(Check);

await ClientQualityWorkspace1HundredStageSmoke.RunAsync(Check);
await ClientQualityWorkspace2HundredStageSmoke.RunAsync(Check);
await ClientQualityWorkspace3HundredStageSmoke.RunAsync(Check);
await ClientQualityWorkspace4HundredStageSmoke.RunAsync(Check);
await ClientQualityWorkspace5HundredStageSmoke.RunAsync(Check);

await ClientProductionProgress1HundredStageSmoke.RunAsync(Check);
await ClientProductionProgress2HundredStageSmoke.RunAsync(Check);
await ClientProductionProgress3HundredStageSmoke.RunAsync(Check);
await ClientProductionProgress4HundredStageSmoke.RunAsync(Check);
await ClientProductionProgress5HundredStageSmoke.RunAsync(Check);

await ClientQualitySessionBoundary1HundredStageSmoke.RunAsync(Check);
await ClientQualitySessionBoundary2HundredStageSmoke.RunAsync(Check);
await ClientQualitySessionBoundary3HundredStageSmoke.RunAsync(Check);
await ClientQualitySessionBoundary4HundredStageSmoke.RunAsync(Check);
await ClientQualitySessionBoundary5HundredStageSmoke.RunAsync(Check);

await ClientAcquisitionWorkspace1HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionWorkspace2HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionWorkspace3HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionWorkspace4HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionWorkspace5HundredStageSmoke.RunAsync(Check);

await ClientAcquisitionCommandGate1HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCommandGate2HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCommandGate3HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCommandGate4HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCommandGate5HundredStageSmoke.RunAsync(Check);

await ClientAcquisitionCatalog1HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCatalog2HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCatalog3HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCatalog4HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionCatalog5HundredStageSmoke.RunAsync(Check);

await ClientProgramStepSelection1HundredStageSmoke.RunAsync(Check);
await ClientProgramStepSelection2HundredStageSmoke.RunAsync(Check);
await ClientProgramStepSelection3HundredStageSmoke.RunAsync(Check);
await ClientProgramStepSelection4HundredStageSmoke.RunAsync(Check);
await ClientProgramStepSelection5HundredStageSmoke.RunAsync(Check);

await ClientResultHistorySelection1HundredStageSmoke.RunAsync(Check);
await ClientResultHistorySelection2HundredStageSmoke.RunAsync(Check);
await ClientResultHistorySelection3HundredStageSmoke.RunAsync(Check);
await ClientResultHistorySelection4HundredStageSmoke.RunAsync(Check);
await ClientResultHistorySelection5HundredStageSmoke.RunAsync(Check);

await ClientQualityFindingSelection1HundredStageSmoke.RunAsync(Check);
await ClientQualityFindingSelection2HundredStageSmoke.RunAsync(Check);
await ClientQualityFindingSelection3HundredStageSmoke.RunAsync(Check);
await ClientQualityFindingSelection4HundredStageSmoke.RunAsync(Check);
await ClientQualityFindingSelection5HundredStageSmoke.RunAsync(Check);

await ClientAcquisitionPreview1HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionPreview2HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionPreview3HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionPreview4HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionPreview5HundredStageSmoke.RunAsync(Check);

await ProductionSessionProgressMetadata1HundredStageSmoke.RunAsync(Check);
await ProductionSessionProgressMetadata2HundredStageSmoke.RunAsync(Check);
await ProductionSessionProgressMetadata3HundredStageSmoke.RunAsync(Check);
await ProductionSessionProgressMetadata4HundredStageSmoke.RunAsync(Check);
await ProductionSessionProgressMetadata5HundredStageSmoke.RunAsync(Check);
await ClientRoiImageSizeBinding1HundredStageSmoke.RunAsync(Check);
await ClientRoiImageSizeBinding2HundredStageSmoke.RunAsync(Check);
await ClientRoiImageSizeBinding3HundredStageSmoke.RunAsync(Check);
await ClientRoiImageSizeBinding4HundredStageSmoke.RunAsync(Check);
await ClientRoiImageSizeBinding5HundredStageSmoke.RunAsync(Check);

await ClientHomePresentation1HundredStageSmoke.RunAsync(Check);
await ClientHomePresentation2HundredStageSmoke.RunAsync(Check);
await ClientHomePresentation3HundredStageSmoke.RunAsync(Check);
await ClientHomePresentation4HundredStageSmoke.RunAsync(Check);
await ClientHomePresentation5HundredStageSmoke.RunAsync(Check);

await ClientAcquisitionFaultState1HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionFaultState2HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionFaultState3HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionFaultState4HundredStageSmoke.RunAsync(Check);
await ClientAcquisitionFaultState5HundredStageSmoke.RunAsync(Check);

await ClientInspectionExecutionRecovery1HundredStageSmoke.RunAsync(Check);
await ClientInspectionExecutionRecovery2HundredStageSmoke.RunAsync(Check);
await ClientInspectionExecutionRecovery3HundredStageSmoke.RunAsync(Check);
await ClientInspectionExecutionRecovery4HundredStageSmoke.RunAsync(Check);
await ClientInspectionExecutionRecovery5HundredStageSmoke.RunAsync(Check);

await ClientInspectionWorkflow1HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkflow2HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkflow3HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkflow4HundredStageSmoke.RunAsync(Check);
await ClientInspectionWorkflow5HundredStageSmoke.RunAsync(Check);

await ClientSimulationQualityEvaluation1HundredStageSmoke.RunAsync(Check);
await ClientSimulationQualityEvaluation2HundredStageSmoke.RunAsync(Check);
await ClientSimulationQualityEvaluation3HundredStageSmoke.RunAsync(Check);
await ClientSimulationQualityEvaluation4HundredStageSmoke.RunAsync(Check);
await ClientSimulationQualityEvaluation5HundredStageSmoke.RunAsync(Check);

if(failures.Count>0)
{
    foreach(var failure in failures)
        Console.Error.WriteLine($"FAIL: {failure}");

    return 1;
}

Console.WriteLine("Asun.Platform.ClientIntegration smoke tests passed.");
return 0;
