var failures=new List<string>();

void Check(bool condition,string message)
{
    if(!condition)
        failures.Add(message);
}


await ProductionQualityEvidenceReplayBundleHundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReplayDescriptor1HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReplayDescriptor2HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReplayDescriptor3HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReplayDescriptor4HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReplayDescriptor5HundredStageSmoke.RunAsync(Check);

await ProductionQualityEvidenceReleaseReplayBinding1HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReleaseReplayBinding2HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReleaseReplayBinding3HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReleaseReplayBinding4HundredStageSmoke.RunAsync(Check);
await ProductionQualityEvidenceReleaseReplayBinding5HundredStageSmoke.RunAsync(Check);

await UnifiedReplayClosure1HundredStageSmoke.RunAsync(Check);
await UnifiedReplayClosure2HundredStageSmoke.RunAsync(Check);
await UnifiedReplayClosure3HundredStageSmoke.RunAsync(Check);
await UnifiedReplayClosure4HundredStageSmoke.RunAsync(Check);
await UnifiedReplayClosure5HundredStageSmoke.RunAsync(Check);

await ProductionMeasurementQualityEvidenceReleaseProvenanceDescriptor1HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseProvenanceDescriptor2HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseProvenanceDescriptor3HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseProvenanceDescriptor4HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseProvenanceDescriptor5HundredStageSmoke.RunAsync(Check);

await ProductionMeasurementQualityEvidenceReleaseReplayDescriptor1HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseReplayDescriptor2HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseReplayDescriptor3HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseReplayDescriptor4HundredStageSmoke.RunAsync(Check);
await ProductionMeasurementQualityEvidenceReleaseReplayDescriptor5HundredStageSmoke.RunAsync(Check);


await ProductionExecutionProvenanceAuditClosure1HundredStageSmoke.RunAsync(Check);
await ProductionExecutionProvenanceAuditClosure2HundredStageSmoke.RunAsync(Check);
await ProductionExecutionProvenanceAuditClosure3HundredStageSmoke.RunAsync(Check);
await ProductionExecutionProvenanceAuditClosure4HundredStageSmoke.RunAsync(Check);
await ProductionExecutionProvenanceAuditClosure5HundredStageSmoke.RunAsync(Check);

await ProductionExecutionReleaseCandidateAuditClosure1HundredStageSmoke.RunAsync(Check);
await ProductionExecutionReleaseCandidateAuditClosure2HundredStageSmoke.RunAsync(Check);
await ProductionExecutionReleaseCandidateAuditClosure3HundredStageSmoke.RunAsync(Check);
await ProductionExecutionReleaseCandidateAuditClosure4HundredStageSmoke.RunAsync(Check);
await ProductionExecutionReleaseCandidateAuditClosure5HundredStageSmoke.RunAsync(Check);

await ProductionReleaseCandidatePcbAuditReplayClosure1HundredStageSmoke.RunAsync(Check);
await ProductionReleaseCandidatePcbAuditReplayClosure2HundredStageSmoke.RunAsync(Check);
await ProductionReleaseCandidatePcbAuditReplayClosure3HundredStageSmoke.RunAsync(Check);
await ProductionReleaseCandidatePcbAuditReplayClosure4HundredStageSmoke.RunAsync(Check);
await ProductionReleaseCandidatePcbAuditReplayClosure5HundredStageSmoke.RunAsync(Check);
await PcbEvidenceReleaseAuditTraceReplayDescriptor1HundredStageSmoke.RunAsync(Check);
await PcbEvidenceReleaseAuditTraceReplayDescriptor2HundredStageSmoke.RunAsync(Check);
await PcbEvidenceReleaseAuditTraceReplayDescriptor3HundredStageSmoke.RunAsync(Check);
await PcbEvidenceReleaseAuditTraceReplayDescriptor4HundredStageSmoke.RunAsync(Check);
await PcbEvidenceReleaseAuditTraceReplayDescriptor5HundredStageSmoke.RunAsync(Check);

await ProductionCaptureEvidenceReplayBinding1HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReplayBinding2HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReplayBinding3HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReplayBinding4HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReplayBinding5HundredStageSmoke.RunAsync(Check);

await ProductionCaptureEvidenceReleaseReplayBinding1HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseReplayBinding2HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseReplayBinding3HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseReplayBinding4HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseReplayBinding5HundredStageSmoke.RunAsync(Check);

await ProductionCaptureEvidenceReleaseAuditTraceReplayBinding1HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseAuditTraceReplayBinding2HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseAuditTraceReplayBinding3HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseAuditTraceReplayBinding4HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceReleaseAuditTraceReplayBinding5HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceAuditReplayConvergence1HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceAuditReplayConvergence2HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceAuditReplayConvergence3HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceAuditReplayConvergence4HundredStageSmoke.RunAsync(Check);
await ProductionCaptureEvidenceAuditReplayConvergence5HundredStageSmoke.RunAsync(Check);
await ProductionCapturePcbAuditReplayConvergence1HundredStageSmoke.RunAsync(Check);
await ProductionCapturePcbAuditReplayConvergence2HundredStageSmoke.RunAsync(Check);
await ProductionCapturePcbAuditReplayConvergence3HundredStageSmoke.RunAsync(Check);
await ProductionCapturePcbAuditReplayConvergence4HundredStageSmoke.RunAsync(Check);
await ProductionCapturePcbAuditReplayConvergence5HundredStageSmoke.RunAsync(Check);
await ProductionSimulationRenderReplayConvergence1HundredStageSmoke.RunAsync(Check);
await ProductionSimulationRenderReplayConvergence2HundredStageSmoke.RunAsync(Check);
await ProductionSimulationRenderReplayConvergence3HundredStageSmoke.RunAsync(Check);
await ProductionSimulationRenderReplayConvergence4HundredStageSmoke.RunAsync(Check);
await ProductionSimulationRenderReplayConvergence5HundredStageSmoke.RunAsync(Check);
await PcbExecutionRoiReplayBinding1HundredStageSmoke.RunAsync(Check);
await PcbExecutionRoiReplayBinding2HundredStageSmoke.RunAsync(Check);
await PcbExecutionRoiReplayBinding3HundredStageSmoke.RunAsync(Check);
await PcbExecutionRoiReplayBinding4HundredStageSmoke.RunAsync(Check);
await PcbExecutionRoiReplayBinding5HundredStageSmoke.RunAsync(Check);

if(failures.Count>0)
{
    foreach(var failure in failures)
        Console.Error.WriteLine($"FAIL: {failure}");

    return 1;
}

Console.WriteLine("Asun.Platform.ReplayIntegration smoke tests passed.");
return 0;
